### ISSUE TITLE
Update versioncode

### ISSUE THREAD

**Issue by krt16s** [Yonjuni/ExaltedDicer#2]
Your latest changes reset the versioncode to 1 in the build.gradle file:

````
        versionCode 1
        versionName "1.0"
````

This breaks updates for users of existing users. The last versioncode I have on record is version 2.0, VC 2. Could you update the versioncode to 3+ to allow updates?

**Comment by Yonjuni** [comment]
Okay, is done

**Comment by krt16s** [comment]
Thanks for the lightning fast response :) !
